export const theme = {
  colors: {
    common: {
      black: "#0D0D0D",
      blackFaded: "#101010",
    },
    background: {
      light: "#F2F2F2",
      default: "#E6E6E6",
      dark: "#D9D9D9",
    },
    text: {
      default: "#1A1A1A",
      muted: "#4D4D4D",
    },
    border: {
      default: "#404040",
      muted: "#8C8C8C",
    },
    accent: {
      primary: "#1CE12F",
      primaryFaded: "#EC7985",
      secondary: "#4068EE",
      secondaryFaded: "#7390F2",
    },
    warnings: {
      success: "#43B534",
      info: "#4F6FDA",
      danger: "#DA4F4F",
      warning: "#D8B233",
    },
  },
  sizes: {
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "7": "28px",
    "8": "32px",
    "9": "36px",
    "10": "40px",
    "11": "44px",
    "12": "48px", 
    "13": "52px", 
    "14": "56px", 
    "15": "60px", 
    "16": "64px", 
  },
  fonts: {
    regular: "FigtreeRegular",
    black: "FigtreeBlack",
    blackItalic: "FigtreeBlackItalic",
    bold: "FigtreeBold",
    boldItalic: "FigtreeBoldItalic",
    extraBold: "FigtreeExtraBold",
    extraBoldItalic: "FigtreeExtraBoldItalic",
    italic: "FigtreeItalic",
    light: "FigtreeLight",
    lightItalic: "FigtreeLightItalic",
    medium: "FigtreeMedium",
    mediumItalic: "FigtreeMediumItalic",
    semiBold: "FigtreeSemiBold",
    semiBoldItalic: "FigtreeSemiBoldItalic",
  }
};
