export type UserState = {
  isLoggedIn: boolean;
  setIsLoggedIn: (isLoggedIn: boolean) => void;
  isLoggingIn: boolean;
  setIsLoggingIn: (isLoggingIn: boolean) => void;
  needsRegistration: boolean;
  setNeedsRegistration: (needsRegistration: boolean) => void;
  userId: string | null;
  setUserId: (personId: string | null) => void;
  username: string | null;
  setUsername: (username: string | null) => void;
  email: string | null;
  setEmail: (email: string | null) => void;
  role: string | null;
  setRole: (role: string | null) => void;
  token: string | null;
  setToken: (token: string | null) => void;
  phoneNumber: string | null;
  setPhoneNumber: (phoneNumber: string | null) => void;
  birthDate: string | null;
  setBirthDate: (birthDate: string | null) => void;
  weightKg: number | null;
  setWeightKg: (weightKg: number | null) => void;
  heightCm: number | null;
  setHeightCm: (heightCm: number | null) => void;
  signOut: () => void;
  setPersonData: (person: {
    id: string;
    name: string;
    email: string;
    username: string;
    phone: string | null;
    birthDate: string | null;
    weightKg: number | null;
    heightCm: number | null;
  }) => void;
};
